services:
    app:
        image: vova0911/vpkg:amd64_latest
        restart: always
        command: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app
        volumes: ['/home/vova/script_files/vpkg:/root/script_files/vpkg']
    nginx:
        image: vova0911/nginx_images:amd64_latest
        container_name: nginx
        restart: always
        depends_on:
            - app
        ports:
            - 85:80

