services:
    app:
        image: vova0911/:armhf_latest
        restart: always
        command: 
        volumes: ['/home/vova/script_files/:/root/script_files/']
        
        privileged: true
        ports:
          - 5000:5000
    nginx:
        image: vova0911/nginx_images:armhf_latest
        container_name: nginx
        restart: always
        depends_on:
            - app
        ports:
            - 85:80

